version: '3.8'
services:
  api:
    image: fjplaurr/talktalk-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5002:${API_PORT}
    environment:
      MONGO_URI: ${MONGO_URI}
      API_PORT: ${API_PORT}
